/**
 * 给花园前端 Remotion Player 用的注册表（不 registerRoot，避免污染 Next）。
 * Studio / CLI 仍走 src/index.ts。
 *
 * AUTO-GENERATED by native:algo_viz_create — 勿手改。
 * 事实源：src/registry-meta.json
 */
import type { ComponentType } from "react";
import { PpoClip } from "./compositions/PpoClip";
import { ArVsDiffusion } from "./compositions/ArVsDiffusion";
import { MaskedDiffusion } from "./compositions/MaskedDiffusion";

export type AlgoVizEntry = {
  id: string;
  component: ComponentType<Record<string, unknown>>;
  durationInFrames: number;
  fps: number;
  width: number;
  height: number;
  defaultProps: Record<string, unknown>;
};

export const ALGO_VIZ_REGISTRY: Record<string, AlgoVizEntry> = {
  PpoClip: {
    id: "PpoClip",
    component: PpoClip as ComponentType<Record<string, unknown>>,
    durationInFrames: 720,
    fps: 30,
    width: 1280,
    height: 720,
    defaultProps: {"epsilon":0.2,"title":"PPO-Clip：信任域的一阶近似"} as Record<string, unknown>,
  },
  ArVsDiffusion: {
    id: "ArVsDiffusion",
    component: ArVsDiffusion as ComponentType<Record<string, unknown>>,
    durationInFrames: 480,
    fps: 30,
    width: 1280,
    height: 720,
    defaultProps: {} as Record<string, unknown>,
  },
  MaskedDiffusion: {
    id: "MaskedDiffusion",
    component: MaskedDiffusion as ComponentType<Record<string, unknown>>,
    durationInFrames: 360,
    fps: 30,
    width: 1280,
    height: 720,
    defaultProps: {} as Record<string, unknown>,
  },
};

export function getAlgoViz(id: string): AlgoVizEntry | null {
  return ALGO_VIZ_REGISTRY[id] ?? ALGO_VIZ_REGISTRY[id.trim()] ?? null;
}

export {
  PpoClip,
  ArVsDiffusion,
  MaskedDiffusion,
};
