/**
 * 算法动画注册表：registry-meta.json 为事实源，registry.ts 由工具生成。
 * Agent 经 native:algo_viz_create 写入 composition + 更新 meta + 重生 registry。
 */
import fs from "fs";
import path from "path";
import type { AppConfig } from "./config.js";
import { resolveSafePath, resolveWithinDir, assertPathWithinDir } from "./safePath.js";

export const ALGO_VIZ_PKG = "apps/algo-viz";
export const ALGO_VIZ_META_REL = "apps/algo-viz/src/registry-meta.json";
export const ALGO_VIZ_REGISTRY_REL = "apps/algo-viz/src/registry.ts";
export const ALGO_VIZ_COMPOSITIONS_REL = "apps/algo-viz/src/compositions";

export type AlgoVizMetaEntry = {
  id: string;
  durationInFrames: number;
  fps: number;
  width: number;
  height: number;
  defaultProps: Record<string, unknown>;
};

export type AlgoVizMetaFile = {
  entries: AlgoVizMetaEntry[];
};

const COMPOSITION_ID_RE = /^[A-Z][A-Za-z0-9]*$/;

export function assertCompositionId(id: string): void {
  if (!COMPOSITION_ID_RE.test(id)) {
    throw new Error(
      `compositionId 须为 PascalCase 标识符（如 PpoClip / ArVsDiffusion），收到：${id}`,
    );
  }
}

/** 源码须具名导出与 id 同名的组件（const / function / export { Id }） */
export function assertSourceExportsComposition(source: string, id: string): void {
  const patterns = [
    new RegExp(`export\\s+(?:const|function|class)\\s+${id}\\b`),
    new RegExp(`export\\s*\\{[^}]*\\b${id}\\b[^}]*\\}`),
  ];
  if (!patterns.some((re) => re.test(source))) {
    throw new Error(
      `source 须具名导出组件 ${id}（export const ${id} / export function ${id} / export { ${id} }）`,
    );
  }
}

function algoVizRootAbs(config: AppConfig): string {
  return resolveSafePath(config, ALGO_VIZ_PKG);
}

function metaAbs(config: AppConfig): string {
  return resolveSafePath(config, ALGO_VIZ_META_REL);
}

function registryAbs(config: AppConfig): string {
  return resolveSafePath(config, ALGO_VIZ_REGISTRY_REL);
}

function compositionAbs(config: AppConfig, id: string): string {
  const root = algoVizRootAbs(config);
  const abs = resolveWithinDir(path.join(root, "src", "compositions"), `${id}.tsx`);
  assertPathWithinDir(root, abs);
  return abs;
}

export function readAlgoVizMeta(config: AppConfig): AlgoVizMetaFile {
  const abs = metaAbs(config);
  if (!fs.existsSync(abs)) {
    return { entries: [] };
  }
  const raw = JSON.parse(fs.readFileSync(abs, "utf8")) as AlgoVizMetaFile;
  if (!raw || !Array.isArray(raw.entries)) {
    throw new Error(`${ALGO_VIZ_META_REL} 格式无效：需要 { entries: [...] }`);
  }
  return raw;
}

export function writeAlgoVizMeta(config: AppConfig, meta: AlgoVizMetaFile): void {
  const abs = metaAbs(config);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, `${JSON.stringify(meta, null, 2)}\n`, "utf8");
}

/** 由 meta 生成 registry.ts 全文 */
export function renderAlgoVizRegistryTs(meta: AlgoVizMetaFile): string {
  const ids = meta.entries.map((e) => e.id);
  const imports = ids
    .map((id) => `import { ${id} } from "./compositions/${id}";`)
    .join("\n");

  const body = meta.entries
    .map((e) => {
      const propsJson = JSON.stringify(e.defaultProps ?? {});
      return `  ${e.id}: {
    id: "${e.id}",
    component: ${e.id} as ComponentType<Record<string, unknown>>,
    durationInFrames: ${Number(e.durationInFrames)},
    fps: ${Number(e.fps)},
    width: ${Number(e.width)},
    height: ${Number(e.height)},
    defaultProps: ${propsJson} as Record<string, unknown>,
  },`;
    })
    .join("\n");

  const reExports =
    ids.length === 0
      ? ""
      : `\nexport {\n${ids.map((id) => `  ${id},`).join("\n")}\n};\n`;

  return `/**
 * 给花园前端 Remotion Player 用的注册表（不 registerRoot，避免污染 Next）。
 * Studio / CLI 仍走 src/index.ts。
 *
 * AUTO-GENERATED by native:algo_viz_create — 勿手改。
 * 事实源：src/registry-meta.json
 */
import type { ComponentType } from "react";
${imports ? `${imports}\n` : ""}
export type AlgoVizEntry = {
  id: string;
  component: ComponentType<Record<string, unknown>>;
  durationInFrames: number;
  fps: number;
  width: number;
  height: number;
  defaultProps: Record<string, unknown>;
};

export const ALGO_VIZ_REGISTRY: Record<string, AlgoVizEntry> = {
${body}
};

export function getAlgoViz(id: string): AlgoVizEntry | null {
  return ALGO_VIZ_REGISTRY[id] ?? ALGO_VIZ_REGISTRY[id.trim()] ?? null;
}
${reExports}`;
}

export function writeAlgoVizRegistryTs(config: AppConfig, meta: AlgoVizMetaFile): void {
  const abs = registryAbs(config);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, renderAlgoVizRegistryTs(meta), "utf8");
}

export type UpsertAlgoVizInput = {
  compositionId: string;
  source: string;
  durationInFrames?: number;
  fps?: number;
  width?: number;
  height?: number;
  defaultProps?: Record<string, unknown>;
  /** 可选分镜 JSON，写入 src/data/{id}-choreography.json */
  choreography?: unknown;
  overwrite?: boolean;
};

export type UpsertAlgoVizResult = {
  compositionId: string;
  compositionPath: string;
  metaPath: string;
  registryPath: string;
  choreographyPath?: string;
  created: boolean;
  vizFenceExample: string;
};

export function upsertAlgoVizComposition(
  config: AppConfig,
  input: UpsertAlgoVizInput,
): UpsertAlgoVizResult {
  const id = String(input.compositionId ?? "").trim();
  assertCompositionId(id);
  const source = String(input.source ?? "");
  if (!source.trim()) throw new Error("source 不能为空");
  assertSourceExportsComposition(source, id);

  if (!fs.existsSync(algoVizRootAbs(config))) {
    throw new Error(`未找到 ${ALGO_VIZ_PKG}，请先脚手架算法动画工程`);
  }

  const compAbs = compositionAbs(config, id);
  const existed = fs.existsSync(compAbs);
  const overwrite = input.overwrite !== false;
  if (existed && !overwrite) {
    throw new Error(`composition ${id} 已存在；若要覆盖请传 overwrite: true`);
  }

  fs.mkdirSync(path.dirname(compAbs), { recursive: true });
  fs.writeFileSync(compAbs, source.endsWith("\n") ? source : `${source}\n`, "utf8");

  let choreographyPath: string | undefined;
  if (input.choreography !== undefined && input.choreography !== null) {
    const root = algoVizRootAbs(config);
    const choreoAbs = resolveWithinDir(
      path.join(root, "src", "data"),
      `${id}-choreography.json`,
    );
    assertPathWithinDir(root, choreoAbs);
    fs.mkdirSync(path.dirname(choreoAbs), { recursive: true });
    const text =
      typeof input.choreography === "string"
        ? input.choreography
        : `${JSON.stringify(input.choreography, null, 2)}\n`;
    fs.writeFileSync(choreoAbs, text.endsWith("\n") ? text : `${text}\n`, "utf8");
    choreographyPath = path.relative(config.projectRoot, choreoAbs).replace(/\\/g, "/");
  }

  const meta = readAlgoVizMeta(config);
  const nextEntry: AlgoVizMetaEntry = {
    id,
    durationInFrames: Math.max(1, Number(input.durationInFrames ?? 180)),
    fps: Math.max(1, Number(input.fps ?? 30)),
    width: Math.max(1, Number(input.width ?? 1280)),
    height: Math.max(1, Number(input.height ?? 720)),
    defaultProps:
      input.defaultProps && typeof input.defaultProps === "object"
        ? (input.defaultProps as Record<string, unknown>)
        : {},
  };
  const idx = meta.entries.findIndex((e) => e.id === id);
  if (idx >= 0) meta.entries[idx] = nextEntry;
  else meta.entries.push(nextEntry);

  writeAlgoVizMeta(config, meta);
  writeAlgoVizRegistryTs(config, meta);

  const propsLines = Object.entries(nextEntry.defaultProps)
    .slice(0, 6)
    .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
    .join("\n");

  return {
    compositionId: id,
    compositionPath: path.relative(config.projectRoot, compAbs).replace(/\\/g, "/"),
    metaPath: ALGO_VIZ_META_REL,
    registryPath: ALGO_VIZ_REGISTRY_REL,
    choreographyPath,
    created: !existed,
    vizFenceExample: [
      "```viz",
      `composition: ${id}`,
      propsLines,
      "```",
    ]
      .filter(Boolean)
      .join("\n"),
  };
}
