/**
 * Hermes B：从经验生成 Skill draft（enabled=false + 可执行 run）
 */

import { beforeEach, describe, expect, it, vi } from "vitest";

const writeMock = vi.hoisted(() => vi.fn());
const readMock = vi.hoisted(() => vi.fn());

vi.mock("../infra/memoryRepository.js", () => ({
  createMemoryRepository: () => ({
    write: writeMock,
    read: readMock,
  }),
}));

import {
  buildDraftSkillCode,
  generateSkillFromExperience,
} from "../infra/agentEvolution.js";
import { getAllowedToolsForTier } from "../infra/swarmPermissionGuard.js";

describe("buildDraftSkillCode", () => {
  it("生成含 run() 的可执行 draft 代码", () => {
    const code = buildDraftSkillCode({
      skillName: "demo",
      tools: ["native:web_search", "native:read_file"],
      experienceCount: 5,
      frequency: 3,
    });
    expect(/\bfunction\s+run\s*\(/.test(code)).toBe(true);
    expect(code).toContain("draft_skill");
    expect(code).toContain("native:web_search");
  });
});

describe("generateSkillFromExperience", () => {
  beforeEach(() => {
    readMock.mockReset();
    writeMock.mockReset();
  });

  it("经验不足返回失败", async () => {
    readMock.mockResolvedValue([]);
    const prisma = {
      agent: {
        findUnique: vi.fn(async () => ({
          id: "a1",
          status: "active",
          workspaceId: null,
        })),
      },
      log: { create: vi.fn(async () => ({})) },
    } as any;
    const services = { skill: { create: vi.fn() } } as any;
    const r = await generateSkillFromExperience(prisma, services, "a1", "s", "d");
    expect(r.success).toBe(false);
    expect(r.reason).toMatch(/经验不足/);
    expect(services.skill.create).not.toHaveBeenCalled();
  });

  it("有高频组合时创建 enabled=false draft", async () => {
    const exp = (tools: string[]) => ({
      content: JSON.stringify({
        taskDescription: "t",
        toolsUsed: tools,
        success: true,
        durationMs: 1,
        tokenUsage: null,
        keyLearnings: "ok",
      }),
    });
    readMock.mockResolvedValue([
      exp(["native:web_search", "native:read_file"]),
      exp(["native:read_file", "native:web_search"]),
      exp(["native:web_search", "native:read_file"]),
    ]);

    const create = vi.fn(async (input: any) => ({
      success: true,
      data: { id: "skill-1", ...input },
    }));
    const prisma = {
      agent: {
        findUnique: vi.fn(async () => ({
          id: "a1",
          status: "active",
          workspaceId: "ws-1",
        })),
      },
      log: { create: vi.fn(async () => ({})) },
    } as any;
    const services = { skill: { create } } as any;

    const r = await generateSkillFromExperience(prisma, services, "a1", "ComboSkill", "desc");
    expect(r.success).toBe(true);
    expect(r.draft).toBe(true);
    expect(create).toHaveBeenCalledOnce();
    const arg = create.mock.calls[0]![0];
    expect(arg.enabled).toBe(false);
    expect(/\bfunction\s+run\s*\(/.test(arg.code)).toBe(true);
    const meta = JSON.parse(arg.metaJson);
    expect(meta.autoGenerated).toBe(true);
    expect(meta.draft).toBe(true);
  });
});

describe("Hermes tool tier 硬拦", () => {
  it("sub 可 list/view、不可 manage/discover；manager 可 manage；discover 仅 super", () => {
    const tools = [
      "native:generate_skill_from_experience",
      "native:optimize_agent_prompt",
      "native:skill_enable",
      "native:skill_manage",
      "native:skills_list",
      "native:skill_view",
      "native:skill_discover",
      "native:read_file",
    ];
    const sub = getAllowedToolsForTier("sub", tools);
    expect(sub).toContain("native:read_file");
    expect(sub).toContain("native:skills_list");
    expect(sub).toContain("native:skill_view");
    expect(sub).not.toContain("native:skill_manage");
    expect(sub).not.toContain("native:skill_discover");
    const mgr = getAllowedToolsForTier("manager", tools);
    expect(mgr).toContain("native:skill_manage");
    expect(mgr).toContain("native:skill_enable");
    expect(mgr).not.toContain("native:skill_discover");
    const sup = getAllowedToolsForTier("super", tools);
    expect(sup).toContain("native:skill_discover");
    expect(sup).toContain("native:skill_manage");
  });
});
