/**
 * Agent 工具单元测试 — 共享 fixture
 */

import fs from "fs";
import os from "os";
import path from "path";
import { PACKS_FULL } from "@knowpilot/shared";
import type { AppConfig } from "../../infra/config.js";
import type { NativeToolContext } from "../../infra/nativeTools.js";
import type { AgentToolContext, ParsedAgentTools } from "../../infra/agentTools.js";
import type { SkillEntity } from "../../infra/entityServices/skillService.js";

export function createTempProjectDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "kp-tool-test-"));
}

export function createTestConfig(projectRoot: string, overrides?: Partial<AppConfig>): AppConfig {
  const skillsDefaults = {
    nudgeInterval: 10,
    reviewModel: "auto",
    staleAfterDays: 30,
    archiveAfterDays: 90,
    curatorIntervalHours: 168,
  };
  const goalDefaults = {
    maxTurns: 20,
    deepResearchMaxTurns: 30,
    autonomousMaxTurns: 40,
    autonomousMaxWallClockMs: 1_800_000,
    autonomousRequireExternalGate: true,
    judgeModel: "auto",
  };
  const harnessDefaults = {
    gate: {
      timeoutMs: 180_000,
      presets: {} as Record<string, string>,
    },
  };
  return {
    port: 3010,
    host: "127.0.0.1",
    projectRoot,
    contentDir: path.join(projectRoot, "content"),
    contentPaths: {
      posts: path.join(projectRoot, "content", "posts"),
      knowledge: path.join(projectRoot, "content", "knowledge"),
      resources: path.join(projectRoot, "content", "resources"),
      about: path.join(projectRoot, "content", "about"),
      uploads: path.join(projectRoot, "content", "uploads"),
    },
    configDir: path.join(projectRoot, "config"),
    configPaths: {
      agents: path.join(projectRoot, "config", "agents"),
      skills: path.join(projectRoot, "config", "skills"),
      mcp: path.join(projectRoot, "config", "mcp"),
      memories: path.join(projectRoot, "config", "memories"),
      tasks: path.join(projectRoot, "config", "tasks"),
      prompts: path.join(projectRoot, "config", "prompts"),
      sources: path.join(projectRoot, "config", "sources"),
    },
    dataDir: path.join(projectRoot, "data"),
    dataPaths: {
      approvals: path.join(projectRoot, "data", "approvals"),
      cookies: path.join(projectRoot, "data", "cookies"),
      files: path.join(projectRoot, "data", "files"),
      git: path.join(projectRoot, "data", "git"),
      logs: path.join(projectRoot, "data", "logs"),
      messages: path.join(projectRoot, "data", "messages"),
      sessions: path.join(projectRoot, "data", "sessions"),
      tools: path.join(projectRoot, "data", "tools"),
      toolResults: path.join(projectRoot, "data", "tool-results"),
      workspace: path.join(projectRoot, "data", "workspace"),
      inbox: path.join(projectRoot, "data", "inbox"),
      experiments: path.join(projectRoot, "data", "experiments"),
    },
    inbox: {
      screenshotWatchDir: "",
      defaultGarden: "knowledge",
      zhihuCollectionUrls: [],
    },
    uploadDir: path.join(projectRoot, "content", "uploads"),
    env: "test",
    publicUrl: "",
    corsOrigins: [],
    serverInternalUrl: "http://127.0.0.1:3010",
    webHost: "127.0.0.1",
    emailProvider: "none",
    llm: {
      defaultProvider: "deepseek",
      defaultModel: "deepseek-v4-flash",
      dailyBudget: 0,
      blendedUsdPer1k: 0.0005,
      maxToolRounds: 8,
      maxToolCallsPerRun: 168,
      toolCallTimeoutMs: 30_000,
      toolCallConcurrency: 4,
      maxRetries: 3,
      baseDelayMs: 1000,
      fallbackModels: [],
      providers: {},
    },
    asyncJobs: { maxPerWorkspace: 0, maxQueued: 100, maxConcurrent: 2, maxPerSession: 2, maxLightweightConcurrent: 2, taskTimeoutMs: 60_000, queuedTimeoutMs: 0, maxSubagentsPerSession: 10 },
    ocr: {
      paddleCliPath: path.join(projectRoot, "missing-paddle.py"),
      paddlePythonPath: "python3",
      ppocrHome: path.join(projectRoot, "weights", "ocr", "paddleocr"),
      ocrSpaceApiKey: "",
      ocrSpaceDefaultLang: "chs",
      tesseractLang: "chi_sim+eng",
    },
    stt: {
      pythonPath: "python3",
      whisperModel: "tiny",
      language: "zh",
      ytDlpPath: "yt-dlp",
      scriptPath: "",
      timeoutMs: 60_000,
      downloadTimeoutMs: 60_000,
      maxDurationSec: 120,
    },
    search: {
      tavilyApiKey: "",
      serpApiKey: "",
      baiduQianfanApiKey: "",
      metasoApiKey: "",
      bochaApiKey: "",
      langsearchApiKey: "",
      braveApiKey: "",
      bingApiKey: "",
      enginePriority: "bing_crawler,tavily",
    },
    integrations: {
      feishu: { appId: "", appSecret: "", userAccessToken: "", tenantAccessToken: "" },
      yuque: { session: "", ctoken: "", personalToken: "" },
      github: { token: "" },
    },
    auth: {
      mode: "none",
      password: "",
      token: "",
    },
    cloudflare: {
      tunnelToken: "",
    },
    shell: {
      enabled: true,
      mode: "host_restricted",
      timeoutMs: 30_000,
      maxOutputChars: 12_000,
      shell: "auto",
    },
    stream: {
      ringSize: 100,
      persist: false,
      eventTtlMs: 0,
      cleanupIntervalMs: 0,
      steeringMode: "one-at-a-time",
      followUpMode: "one-at-a-time",
      runTimeoutMs: 300_000,
      runStallTimeoutMs: 120_000,
    },
    compact: {
      enabled: true,
      triggerRatio: 0.75,
      keepRecent: 8,
      keepRecentTokens: 20000,
      summaryModel: "auto",
      microCompact: { enabled: true, toolResultMaxChars: 4000 },
      toolResultOffload: {
        enabled: true,
        thresholdChars: 4000,
        contextWindow: 400,
        chunkStrideChars: 1000,
        retentionDays: 14,
      },
      toolLoopStreakLimit: 3,
      memoryFlush: { enabled: true, maxFacts: 5 },
    },
    heartbeat: {
      decisionEnabled: true,
      quietCap: 8,
      terminalAfterQuiet: 3,
      gateNotifyCooldownMs: 1_800_000,
      loopContract: { maxStaleRounds: 3, maxEvidence: 50 },
    },
    approvalGate: {
      notifyCooldownMs: 1_800_000,
    },
    reflection: { enabled: false, maxRounds: 1, criticModel: "" },
    packs: { ...PACKS_FULL },
    ...overrides,
    // 浅合并会整段覆盖 skills/goal，这里补回默认字段
    memory: {
      queryRewrite: {
        enabled: false,
        model: "auto",
        timeoutMs: 3000,
        ...(overrides?.memory?.queryRewrite ?? {}),
      },
      embedding: {
        enabled: false,
        baseUrl: "",
        apiKey: "",
        model: "text-embedding-3-small",
        topK: 20,
        ...(overrides?.memory?.embedding ?? {}),
      },
    },
    skills: {
      ...skillsDefaults,
      ...(overrides?.skills ?? {}),
    },
    goal: {
      ...goalDefaults,
      ...(overrides?.goal ?? {}),
    },
    harness: {
      ...harnessDefaults,
      ...(overrides?.harness ?? {}),
      gate: {
        ...harnessDefaults.gate,
        ...(overrides?.harness?.gate ?? {}),
        presets: {
          ...harnessDefaults.gate.presets,
          ...(overrides?.harness?.gate?.presets ?? {}),
        },
      },
    },
  };
}

export function createNativeCtx(
  projectRoot: string,
  opts?: {
    config?: Partial<AppConfig>;
    invokeTrpc?: (tool: string, args?: unknown) => Promise<unknown>;
    services?: NativeToolContext["services"];
    prisma?: NativeToolContext["prisma"];
  },
): NativeToolContext {
  const config = createTestConfig(projectRoot, opts?.config);
  return {
    config,
    services: opts?.services ?? ({} as NativeToolContext["services"]),
    prisma: opts?.prisma,
    invokeTrpc: opts?.invokeTrpc ?? (async () => ({ ok: true })),
  };
}

export function createAgentCtx(
  projectRoot: string,
  parsed: ParsedAgentTools,
  opts?: Parameters<typeof createNativeCtx>[1],
): AgentToolContext {
  const base = createNativeCtx(projectRoot, opts);
  return {
    ...base,
    allowedNative: parsed.native,
    allowedSkills: parsed.skills,
    allowedMcpServers: parsed.mcpServers,
  };
}

export function makeSkillEntity(partial: Partial<SkillEntity> & Pick<SkillEntity, "name">): SkillEntity {
  return {
    id: partial.id ?? "skill-id",
    description: partial.description ?? "test skill",
    code: partial.code ?? "# prompt skill",
    icon: partial.icon ?? "Wand2",
    trigger: partial.trigger ?? null,
    enabled: partial.enabled ?? true,
    tags: [],
    metaJson: partial.metaJson ?? null,
    createdAt: partial.createdAt ?? new Date(),
    updatedAt: partial.updatedAt ?? new Date(),
    ...partial,
  };
}

export const ALL_NATIVE_TOOL_NAMES = [
  "web_search",
  "literature_search",
  "literature_get",
  "document_to_markdown",
  "rss_fetch",
  "rss_draft_posts",
  "read_article",
  "dokobot_read",
  "dokobot_search",
  "webbridge_status",
  "webbridge_start",
  "webbridge_command",
  "scrape_web_page",
  "browser_screenshot",
  "scroll_screenshot",
  "save_webpage",
  "download_file",
  "article_material_pack",
  "article_import",
  "article_video_compose",
  "read_image",
  "vision_describe",
  "video_transcript",
  "media_download",
  "audio_transcribe",
  "video_notes",
  "search_arxiv",
  "fetch_arxiv",
  "search_huggingface",
  "fetch_huggingface_model",
  "fetch_huggingface_trending",
  "read_file",
  "write_file",
  "append_to_file",
  "algo_viz_create",
  "algo_viz_list",
  "list_directory",
  "file_rename",
  "file_move",
  "file_copy",
  "search_files",
  "directory_create",
  "file_stat",
  "directory_delete",
  "garden_create",
  "garden_list",
  "garden_get",
  "garden_update",
  "garden_delete",
  "garden_restore",
  "post_create",
  "post_update",
  "post_delete",
  "post_list",
  "post_neighbors",
  "memory_create",
  "memory_update",
  "memory_search",
  "memory_delete",
  "memory_daily_append",
  "memory_daily_search",
  "memory_distill_persona",
  "pinned_memory_read",
  "pinned_memory_write",
  "todo_write",
  "todo_read",
  "session_goal_set",
  "session_goal_status",
  "session_goal_clear",
  "session_goal_pause",
  "session_goal_resume",
  "session_spawn_goal",
  "git_branch",
  "git_checkout",
  "git_clone",
  "git_status",
  "git_log",
  "git_diff",
  "git_commit",
  "git_pull",
  "git_push",
  "file_delete",
  "trash_list",
  "trash_restore",
  "task_run",
  "yuque_get_doc",
  "yuque_list_books",
  "yuque_get_book_toc",
  "yuque_create_book",
  "yuque_update_book",
  "yuque_delete_book",
  "yuque_create_doc",
  "yuque_update_doc",
  "yuque_delete_doc",
  "yuque_session_status",
  "yuque_list_repos",
  "yuque_create_repo",
  "yuque_update_repo",
  "yuque_delete_repo",
  "yuque_list_docs",
  "yuque_create_doc_v2",
  "yuque_update_doc_v2",
  "yuque_delete_doc_v2",
  "platform_login",
  "browser_login_status",
  "platform_doctor",
  "github_search_repos",
  "github_get_repo",
  "github_create_repo",
  "github_update_repo",
  "github_delete_repo",
  "github_get_file",
  "github_create_file",
  "github_update_file",
  "github_delete_file",
  "github_list_issues",
  "github_get_issue",
  "github_create_issue",
  "github_update_issue",
  "github_create_issue_comment",
  "github_list_pull_requests",
  "github_get_pull_request",
  "github_create_pull_request",
  "github_update_pull_request",
  "github_merge_pull_request",
  "github_list_branches",
  "github_get_branch",
  "github_create_branch",
  "github_delete_branch",
  "github_list_workflows",
  "github_trigger_workflow",
  "github_create_release",
  "github_tool",
  "feishu_send_text",
  "feishu_send_message",
  "feishu_get_doc",
  "feishu_create_doc",
  "feishu_update_doc",
  "feishu_append_doc_text",
  "feishu_append_doc_blocks",
  "feishu_delete_doc",
  "feishu_search_docs",
  "feishu_list_permission_members",
  "feishu_add_permission_member",
  "feishu_update_permission_member",
  "feishu_remove_permission_member",
  "feishu_get_permission_public",
  "feishu_update_permission_public",
  "feishu_lookup_user",
  "feishu_add_collaborator_by_contact",
  "feishu_get_wiki_space",
  "feishu_get_wiki_nodes",
  "feishu_create_wiki_node",
  "feishu_create_spreadsheet",
  "feishu_append_spreadsheet_values",
  "feishu_token_status",
  "feishu_refresh_token",
  "feishu_authorize",
  "feishu_list_doc_whiteboards",
  "feishu_list_whiteboard_nodes",
  "feishu_create_whiteboard_nodes",
  "feishu_whiteboard_from_diagram",
  "feishu_delete_whiteboard_nodes",
  "feishu_get_whiteboard_theme",
  "feishu_update_whiteboard_theme",
  "async_task_run",
  "spawn_subagent",
  "async_task_status",
  "async_task_cancel",
  "async_task_resume",
  "run_shell",
  "pinme_upload",
  "wait",
  "sleep",
  "session_clear",
  "session_rotate",
  "session_compact",
  "session_context_usage",
  "session_search",
  "session_message_get",
  "tool_results_list",
  "tool_result_meta",
  // Swarm 管理工具
  "agent_create",
  "agent_update",
  "agent_delete",
  "agent_inspect",
  "agent_send_message",
  "agent_report_back",
  "agent_create_sub",
  "agent_update_sub",
  "agent_delete_sub",
  "agent_notify_parent",
  "swarm_brief",
  "ask_user",
  "workspace_create",
  "workspace_archive",
  "send_email",
  "coze_chat",
  "coze_workflow",
  "dify_chat",
  "dify_workflow",
  "tikhub_request",
  "agent_cron_set",
  "agent_cron_list",
  "agent_cron_clear",
  "zhihu_openapi_search",
  "zhihu_openapi_hot_list",
  "zhihu_openapi_ask",
  "zhihu_openapi_favlists",
  "zhihu_openapi_recent_collections",
  "zhihu_openapi_favlist_contents",
  "inbox_list",
  "inbox_stats",
  "inbox_capture_url",
  "inbox_capture_urls",
  "inbox_start_platform_sync",
  "inbox_platform_sync_status",
  "inbox_cancel_platform_sync",
  "inbox_sync_zhihu",
  "inbox_sync_xhs",
  "inbox_sync_bilibili",
  "inbox_scan_screenshots",
  "inbox_ingest_wechat",
  "inbox_enrich",
  "inbox_distill",
  "inbox_ignore",
  "free_api_keys_list",
  "free_api_keys_fetch",
  "free_models_list",
  "skills_list",
  "skill_view",
  "skill_manage",
  "skill_discover",
  "skill_enable",
  "skill_promote",
  "experiment_begin",
  "experiment_decide",
  "experiment_list",
  "experiment_get",
  "experiment_rollback",
  "experiment_branch",
  "harness_refine",
  "harness_gate_run",
  "autonomous_gate",
  "optimize_agent_prompt",
  "generate_skill_from_experience",
  "swarm_export_trace",
  "swarm_stage_write",
  "swarm_stage_list",
  "swarm_stage_read",
  "swanlab_status",
  "swanlab_user_info",
  "swanlab_project_list",
  "swanlab_project_create",
  "swanlab_run_list",
  "swanlab_run_info",
  "swanlab_run_summary",
  "swanlab_run_metrics",
  "swanlab_run_series",
  "swanlab_scaffold_train",
  "send_qq_text",
  "send_qq_image",
  "send_qq_video",
  "send_qq_file",
  "send_qq_voice",
  "delete_qq_message",
  "voice_list",
  "voice_clone",
  "voice_delete",
  "voice_synthesize",
  "audio_slice",
] as const;
