[Portal.OSS]
CatalogRefreshMin=1800
CatalogRefreshMax=3600
EmsMaxCount=1000
EntitlementRefreshMin=600
EntitlementRefreshMax=1200

[Portal.SelfUpdate]
RefreshTimeMin=14400
RefreshTimeMax=28800

[TabDoesRequirePermission]
viper=false

; Legacy values for older launchers
[Portal.SelfUpdate]
RefreshTime=14400

; Legacy values for older launchers
[Portal.OSS]
CatalogRefresh=1800
EmsRefresh=1200
EntitlementRefresh=600
